safe:        false
port:        3000
baseurl:    /

source:      .
destination: ./_site
plugins_dir:     ./_plugins
exclude:     [scripts, fabfile.py]

future:      true
lsi:         false
highlighter: rouge
markdown:    kramdown
permalink:   /blog/:title


rdiscount:
  extensions: []

kramdown:
  auto_ids: true,
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false
  
  coderay:
    coderay_wrap: div
    coderay_line_numbers: inline
    coderay_line_numbers_start: 1
    coderay_tab_width: 4
    coderay_bold_every: 10
    coderay_css: style


defaults:
    - scope:
        path: ""
        type: posts
      values:
        layout: post
